/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import se.olander.categories.jooq.categories.tables.CategoryItemAlternativeSpelling;
import se.olander.categories.jooq.categories.tables.records.CategoryItemAlternativeSpellingRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryItemAlternativeSpellingDao extends DAOImpl<CategoryItemAlternativeSpellingRecord, se.olander.categories.jooq.categories.tables.pojos.CategoryItemAlternativeSpelling, Integer> {

    /**
     * Create a new CategoryItemAlternativeSpellingDao without any configuration
     */
    public CategoryItemAlternativeSpellingDao() {
        super(CategoryItemAlternativeSpelling.CATEGORY_ITEM_ALTERNATIVE_SPELLING, se.olander.categories.jooq.categories.tables.pojos.CategoryItemAlternativeSpelling.class);
    }

    /**
     * Create a new CategoryItemAlternativeSpellingDao with an attached configuration
     */
    public CategoryItemAlternativeSpellingDao(Configuration configuration) {
        super(CategoryItemAlternativeSpelling.CATEGORY_ITEM_ALTERNATIVE_SPELLING, se.olander.categories.jooq.categories.tables.pojos.CategoryItemAlternativeSpelling.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(se.olander.categories.jooq.categories.tables.pojos.CategoryItemAlternativeSpelling object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.CategoryItemAlternativeSpelling> fetchById(Integer... values) {
        return fetch(CategoryItemAlternativeSpelling.CATEGORY_ITEM_ALTERNATIVE_SPELLING.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public se.olander.categories.jooq.categories.tables.pojos.CategoryItemAlternativeSpelling fetchOneById(Integer value) {
        return fetchOne(CategoryItemAlternativeSpelling.CATEGORY_ITEM_ALTERNATIVE_SPELLING.ID, value);
    }

    /**
     * Fetch records that have <code>category_id IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.CategoryItemAlternativeSpelling> fetchByCategoryId(Integer... values) {
        return fetch(CategoryItemAlternativeSpelling.CATEGORY_ITEM_ALTERNATIVE_SPELLING.CATEGORY_ID, values);
    }

    /**
     * Fetch records that have <code>category_item_id IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.CategoryItemAlternativeSpelling> fetchByCategoryItemId(Integer... values) {
        return fetch(CategoryItemAlternativeSpelling.CATEGORY_ITEM_ALTERNATIVE_SPELLING.CATEGORY_ITEM_ID, values);
    }

    /**
     * Fetch records that have <code>spelling IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.CategoryItemAlternativeSpelling> fetchBySpelling(String... values) {
        return fetch(CategoryItemAlternativeSpelling.CATEGORY_ITEM_ALTERNATIVE_SPELLING.SPELLING, values);
    }
}
