/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import se.olander.categories.jooq.categories.Categories;
import se.olander.categories.jooq.categories.Keys;
import se.olander.categories.jooq.categories.tables.records.CategoryItemsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryItems extends TableImpl<CategoryItemsRecord> {

    private static final long serialVersionUID = 462396774;

    /**
     * The reference instance of <code>categories.category_items</code>
     */
    public static final CategoryItems CATEGORY_ITEMS = new CategoryItems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CategoryItemsRecord> getRecordType() {
        return CategoryItemsRecord.class;
    }

    /**
     * The column <code>categories.category_items.id</code>.
     */
    public final TableField<CategoryItemsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>categories.category_items.name</code>.
     */
    public final TableField<CategoryItemsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>categories.category_items.category_id</code>.
     */
    public final TableField<CategoryItemsRecord, Integer> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>categories.category_items</code> table reference
     */
    public CategoryItems() {
        this("category_items", null);
    }

    /**
     * Create an aliased <code>categories.category_items</code> table reference
     */
    public CategoryItems(String alias) {
        this(alias, CATEGORY_ITEMS);
    }

    private CategoryItems(String alias, Table<CategoryItemsRecord> aliased) {
        this(alias, aliased, null);
    }

    private CategoryItems(String alias, Table<CategoryItemsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Categories.CATEGORIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CategoryItemsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CATEGORY_ITEMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CategoryItemsRecord> getPrimaryKey() {
        return Keys.KEY_CATEGORY_ITEMS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CategoryItemsRecord>> getKeys() {
        return Arrays.<UniqueKey<CategoryItemsRecord>>asList(Keys.KEY_CATEGORY_ITEMS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CategoryItemsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CategoryItemsRecord, ?>>asList(Keys.CATEGORY_ITEMS_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategoryItems as(String alias) {
        return new CategoryItems(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CategoryItems rename(String name) {
        return new CategoryItems(name, null);
    }
}
