/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import se.olander.categories.jooq.categories.Categories;
import se.olander.categories.jooq.categories.Keys;
import se.olander.categories.jooq.categories.tables.records.GoogleAccountRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoogleAccount extends TableImpl<GoogleAccountRecord> {

    private static final long serialVersionUID = 263537035;

    /**
     * The reference instance of <code>categories.google_account</code>
     */
    public static final GoogleAccount GOOGLE_ACCOUNT = new GoogleAccount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GoogleAccountRecord> getRecordType() {
        return GoogleAccountRecord.class;
    }

    /**
     * The column <code>categories.google_account.id</code>.
     */
    public final TableField<GoogleAccountRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>categories.google_account.user_id</code>.
     */
    public final TableField<GoogleAccountRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>categories.google_account.external_id</code>.
     */
    public final TableField<GoogleAccountRecord, String> EXTERNAL_ID = createField("external_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>categories.google_account.created_time</code>.
     */
    public final TableField<GoogleAccountRecord, Timestamp> CREATED_TIME = createField("created_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>categories.google_account.updated_time</code>.
     */
    public final TableField<GoogleAccountRecord, Timestamp> UPDATED_TIME = createField("updated_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>categories.google_account</code> table reference
     */
    public GoogleAccount() {
        this("google_account", null);
    }

    /**
     * Create an aliased <code>categories.google_account</code> table reference
     */
    public GoogleAccount(String alias) {
        this(alias, GOOGLE_ACCOUNT);
    }

    private GoogleAccount(String alias, Table<GoogleAccountRecord> aliased) {
        this(alias, aliased, null);
    }

    private GoogleAccount(String alias, Table<GoogleAccountRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Categories.CATEGORIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<GoogleAccountRecord, Integer> getIdentity() {
        return Keys.IDENTITY_GOOGLE_ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GoogleAccountRecord> getPrimaryKey() {
        return Keys.KEY_GOOGLE_ACCOUNT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GoogleAccountRecord>> getKeys() {
        return Arrays.<UniqueKey<GoogleAccountRecord>>asList(Keys.KEY_GOOGLE_ACCOUNT_PRIMARY, Keys.KEY_GOOGLE_ACCOUNT_EXTERNAL_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<GoogleAccountRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GoogleAccountRecord, ?>>asList(Keys.GOOGLE_ACCOUNT_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GoogleAccount as(String alias) {
        return new GoogleAccount(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GoogleAccount rename(String name) {
        return new GoogleAccount(name, null);
    }
}
