/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account implements Serializable {

    private static final long serialVersionUID = -2019898169;

    private Integer   id;
    private Integer   userId;
    private String    emailAddress;
    private String    password;
    private Timestamp createdTime;

    public Account() {}

    public Account(Account value) {
        this.id = value.id;
        this.userId = value.userId;
        this.emailAddress = value.emailAddress;
        this.password = value.password;
        this.createdTime = value.createdTime;
    }

    public Account(
        Integer   id,
        Integer   userId,
        String    emailAddress,
        String    password,
        Timestamp createdTime
    ) {
        this.id = id;
        this.userId = userId;
        this.emailAddress = emailAddress;
        this.password = password;
        this.createdTime = createdTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getEmailAddress() {
        return this.emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Timestamp getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Timestamp createdTime) {
        this.createdTime = createdTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(emailAddress);
        sb.append(", ").append(password);
        sb.append(", ").append(createdTime);

        sb.append(")");
        return sb.toString();
    }
}
