/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryItemAlternativeSpelling implements Serializable {

    private static final long serialVersionUID = 2016037332;

    private Integer id;
    private Integer categoryId;
    private Integer categoryItemId;
    private String  spelling;

    public CategoryItemAlternativeSpelling() {}

    public CategoryItemAlternativeSpelling(CategoryItemAlternativeSpelling value) {
        this.id = value.id;
        this.categoryId = value.categoryId;
        this.categoryItemId = value.categoryItemId;
        this.spelling = value.spelling;
    }

    public CategoryItemAlternativeSpelling(
        Integer id,
        Integer categoryId,
        Integer categoryItemId,
        String  spelling
    ) {
        this.id = id;
        this.categoryId = categoryId;
        this.categoryItemId = categoryItemId;
        this.spelling = spelling;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public Integer getCategoryItemId() {
        return this.categoryItemId;
    }

    public void setCategoryItemId(Integer categoryItemId) {
        this.categoryItemId = categoryItemId;
    }

    public String getSpelling() {
        return this.spelling;
    }

    public void setSpelling(String spelling) {
        this.spelling = spelling;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CategoryItemAlternativeSpelling (");

        sb.append(id);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(categoryItemId);
        sb.append(", ").append(spelling);

        sb.append(")");
        return sb.toString();
    }
}
