/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryItems implements Serializable {

    private static final long serialVersionUID = 106922945;

    private Integer id;
    private String  name;
    private Integer categoryId;

    public CategoryItems() {}

    public CategoryItems(CategoryItems value) {
        this.id = value.id;
        this.name = value.name;
        this.categoryId = value.categoryId;
    }

    public CategoryItems(
        Integer id,
        String  name,
        Integer categoryId
    ) {
        this.id = id;
        this.name = name;
        this.categoryId = categoryId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CategoryItems (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(categoryId);

        sb.append(")");
        return sb.toString();
    }
}
