/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Game implements Serializable {

    private static final long serialVersionUID = -2071977502;

    private Integer   id;
    private String    name;
    private Integer   categoryId;
    private Timestamp timeStart;

    public Game() {}

    public Game(Game value) {
        this.id = value.id;
        this.name = value.name;
        this.categoryId = value.categoryId;
        this.timeStart = value.timeStart;
    }

    public Game(
        Integer   id,
        String    name,
        Integer   categoryId,
        Timestamp timeStart
    ) {
        this.id = id;
        this.name = name;
        this.categoryId = categoryId;
        this.timeStart = timeStart;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public Timestamp getTimeStart() {
        return this.timeStart;
    }

    public void setTimeStart(Timestamp timeStart) {
        this.timeStart = timeStart;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Game (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(timeStart);

        sb.append(")");
        return sb.toString();
    }
}
