/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import se.olander.categories.jooq.categories.tables.Guess;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuessRecord extends UpdatableRecordImpl<GuessRecord> implements Record6<Integer, Integer, Integer, String, Integer, Timestamp> {

    private static final long serialVersionUID = 2037532842;

    /**
     * Setter for <code>categories.guess.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>categories.guess.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>categories.guess.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>categories.guess.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>categories.guess.game_id</code>.
     */
    public void setGameId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>categories.guess.game_id</code>.
     */
    public Integer getGameId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>categories.guess.guess_raw</code>.
     */
    public void setGuessRaw(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>categories.guess.guess_raw</code>.
     */
    public String getGuessRaw() {
        return (String) get(3);
    }

    /**
     * Setter for <code>categories.guess.category_item_id</code>.
     */
    public void setCategoryItemId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>categories.guess.category_item_id</code>.
     */
    public Integer getCategoryItemId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>categories.guess.created_time</code>.
     */
    public void setCreatedTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>categories.guess.created_time</code>.
     */
    public Timestamp getCreatedTime() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, String, Integer, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, String, Integer, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Guess.GUESS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Guess.GUESS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Guess.GUESS.GAME_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Guess.GUESS.GUESS_RAW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Guess.GUESS.CATEGORY_ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Guess.GUESS.CREATED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getGameId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getGuessRaw();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getCategoryItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuessRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuessRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuessRecord value3(Integer value) {
        setGameId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuessRecord value4(String value) {
        setGuessRaw(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuessRecord value5(Integer value) {
        setCategoryItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuessRecord value6(Timestamp value) {
        setCreatedTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuessRecord values(Integer value1, Integer value2, Integer value3, String value4, Integer value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuessRecord
     */
    public GuessRecord() {
        super(Guess.GUESS);
    }

    /**
     * Create a detached, initialised GuessRecord
     */
    public GuessRecord(Integer id, Integer userId, Integer gameId, String guessRaw, Integer categoryItemId, Timestamp createdTime) {
        super(Guess.GUESS);

        set(0, id);
        set(1, userId);
        set(2, gameId);
        set(3, guessRaw);
        set(4, categoryItemId);
        set(5, createdTime);
    }
}
