/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import se.olander.categories.jooq.categories.tables.Participant;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParticipantRecord extends UpdatableRecordImpl<ParticipantRecord> implements Record4<Integer, Integer, Integer, Byte> {

    private static final long serialVersionUID = -1691049425;

    /**
     * Setter for <code>categories.participant.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>categories.participant.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>categories.participant.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>categories.participant.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>categories.participant.game_id</code>.
     */
    public void setGameId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>categories.participant.game_id</code>.
     */
    public Integer getGameId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>categories.participant.admin</code>.
     */
    public void setAdmin(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>categories.participant.admin</code>.
     */
    public Byte getAdmin() {
        return (Byte) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Byte> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Byte> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Participant.PARTICIPANT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Participant.PARTICIPANT.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Participant.PARTICIPANT.GAME_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return Participant.PARTICIPANT.ADMIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getGameId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getAdmin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value3(Integer value) {
        setGameId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord value4(Byte value) {
        setAdmin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParticipantRecord values(Integer value1, Integer value2, Integer value3, Byte value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ParticipantRecord
     */
    public ParticipantRecord() {
        super(Participant.PARTICIPANT);
    }

    /**
     * Create a detached, initialised ParticipantRecord
     */
    public ParticipantRecord(Integer id, Integer userId, Integer gameId, Byte admin) {
        super(Participant.PARTICIPANT);

        set(0, id);
        set(1, userId);
        set(2, gameId);
        set(3, admin);
    }
}
