/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import se.olander.categories.jooq.categories.tables.CategoryItems;
import se.olander.categories.jooq.categories.tables.records.CategoryItemsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryItemsDao extends DAOImpl<CategoryItemsRecord, se.olander.categories.jooq.categories.tables.pojos.CategoryItems, Integer> {

    /**
     * Create a new CategoryItemsDao without any configuration
     */
    public CategoryItemsDao() {
        super(CategoryItems.CATEGORY_ITEMS, se.olander.categories.jooq.categories.tables.pojos.CategoryItems.class);
    }

    /**
     * Create a new CategoryItemsDao with an attached configuration
     */
    public CategoryItemsDao(Configuration configuration) {
        super(CategoryItems.CATEGORY_ITEMS, se.olander.categories.jooq.categories.tables.pojos.CategoryItems.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(se.olander.categories.jooq.categories.tables.pojos.CategoryItems object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.CategoryItems> fetchById(Integer... values) {
        return fetch(CategoryItems.CATEGORY_ITEMS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public se.olander.categories.jooq.categories.tables.pojos.CategoryItems fetchOneById(Integer value) {
        return fetchOne(CategoryItems.CATEGORY_ITEMS.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.CategoryItems> fetchByName(String... values) {
        return fetch(CategoryItems.CATEGORY_ITEMS.NAME, values);
    }

    /**
     * Fetch records that have <code>category_id IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.CategoryItems> fetchByCategoryId(Integer... values) {
        return fetch(CategoryItems.CATEGORY_ITEMS.CATEGORY_ID, values);
    }
}
