/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import se.olander.categories.jooq.categories.tables.GoogleAccount;
import se.olander.categories.jooq.categories.tables.records.GoogleAccountRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoogleAccountDao extends DAOImpl<GoogleAccountRecord, se.olander.categories.jooq.categories.tables.pojos.GoogleAccount, Integer> {

    /**
     * Create a new GoogleAccountDao without any configuration
     */
    public GoogleAccountDao() {
        super(GoogleAccount.GOOGLE_ACCOUNT, se.olander.categories.jooq.categories.tables.pojos.GoogleAccount.class);
    }

    /**
     * Create a new GoogleAccountDao with an attached configuration
     */
    public GoogleAccountDao(Configuration configuration) {
        super(GoogleAccount.GOOGLE_ACCOUNT, se.olander.categories.jooq.categories.tables.pojos.GoogleAccount.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(se.olander.categories.jooq.categories.tables.pojos.GoogleAccount object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.GoogleAccount> fetchById(Integer... values) {
        return fetch(GoogleAccount.GOOGLE_ACCOUNT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public se.olander.categories.jooq.categories.tables.pojos.GoogleAccount fetchOneById(Integer value) {
        return fetchOne(GoogleAccount.GOOGLE_ACCOUNT.ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.GoogleAccount> fetchByUserId(Integer... values) {
        return fetch(GoogleAccount.GOOGLE_ACCOUNT.USER_ID, values);
    }

    /**
     * Fetch records that have <code>external_id IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.GoogleAccount> fetchByExternalId(String... values) {
        return fetch(GoogleAccount.GOOGLE_ACCOUNT.EXTERNAL_ID, values);
    }

    /**
     * Fetch a unique record that has <code>external_id = value</code>
     */
    public se.olander.categories.jooq.categories.tables.pojos.GoogleAccount fetchOneByExternalId(String value) {
        return fetchOne(GoogleAccount.GOOGLE_ACCOUNT.EXTERNAL_ID, value);
    }

    /**
     * Fetch records that have <code>created_time IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.GoogleAccount> fetchByCreatedTime(Timestamp... values) {
        return fetch(GoogleAccount.GOOGLE_ACCOUNT.CREATED_TIME, values);
    }

    /**
     * Fetch records that have <code>updated_time IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.GoogleAccount> fetchByUpdatedTime(Timestamp... values) {
        return fetch(GoogleAccount.GOOGLE_ACCOUNT.UPDATED_TIME, values);
    }
}
