/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import se.olander.categories.jooq.categories.tables.Guess;
import se.olander.categories.jooq.categories.tables.records.GuessRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuessDao extends DAOImpl<GuessRecord, se.olander.categories.jooq.categories.tables.pojos.Guess, Integer> {

    /**
     * Create a new GuessDao without any configuration
     */
    public GuessDao() {
        super(Guess.GUESS, se.olander.categories.jooq.categories.tables.pojos.Guess.class);
    }

    /**
     * Create a new GuessDao with an attached configuration
     */
    public GuessDao(Configuration configuration) {
        super(Guess.GUESS, se.olander.categories.jooq.categories.tables.pojos.Guess.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(se.olander.categories.jooq.categories.tables.pojos.Guess object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.Guess> fetchById(Integer... values) {
        return fetch(Guess.GUESS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public se.olander.categories.jooq.categories.tables.pojos.Guess fetchOneById(Integer value) {
        return fetchOne(Guess.GUESS.ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.Guess> fetchByUserId(Integer... values) {
        return fetch(Guess.GUESS.USER_ID, values);
    }

    /**
     * Fetch records that have <code>game_id IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.Guess> fetchByGameId(Integer... values) {
        return fetch(Guess.GUESS.GAME_ID, values);
    }

    /**
     * Fetch records that have <code>guess_raw IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.Guess> fetchByGuessRaw(String... values) {
        return fetch(Guess.GUESS.GUESS_RAW, values);
    }

    /**
     * Fetch records that have <code>category_item_id IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.Guess> fetchByCategoryItemId(Integer... values) {
        return fetch(Guess.GUESS.CATEGORY_ITEM_ID, values);
    }

    /**
     * Fetch records that have <code>time_guess IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.Guess> fetchByTimeGuess(Timestamp... values) {
        return fetch(Guess.GUESS.TIME_GUESS, values);
    }
}
