/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import se.olander.categories.jooq.categories.tables.Participant;
import se.olander.categories.jooq.categories.tables.records.ParticipantRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParticipantDao extends DAOImpl<ParticipantRecord, se.olander.categories.jooq.categories.tables.pojos.Participant, Integer> {

    /**
     * Create a new ParticipantDao without any configuration
     */
    public ParticipantDao() {
        super(Participant.PARTICIPANT, se.olander.categories.jooq.categories.tables.pojos.Participant.class);
    }

    /**
     * Create a new ParticipantDao with an attached configuration
     */
    public ParticipantDao(Configuration configuration) {
        super(Participant.PARTICIPANT, se.olander.categories.jooq.categories.tables.pojos.Participant.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(se.olander.categories.jooq.categories.tables.pojos.Participant object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.Participant> fetchById(Integer... values) {
        return fetch(Participant.PARTICIPANT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public se.olander.categories.jooq.categories.tables.pojos.Participant fetchOneById(Integer value) {
        return fetchOne(Participant.PARTICIPANT.ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.Participant> fetchByUserId(Integer... values) {
        return fetch(Participant.PARTICIPANT.USER_ID, values);
    }

    /**
     * Fetch records that have <code>game_id IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.Participant> fetchByGameId(Integer... values) {
        return fetch(Participant.PARTICIPANT.GAME_ID, values);
    }

    /**
     * Fetch records that have <code>admin IN (values)</code>
     */
    public List<se.olander.categories.jooq.categories.tables.pojos.Participant> fetchByAdmin(Byte... values) {
        return fetch(Participant.PARTICIPANT.ADMIN, values);
    }
}
