/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account implements Serializable {

    private static final long serialVersionUID = -427162102;

    private Integer   id;
    private Integer   userId;
    private String    emailAddress;
    private String    hash;
    private Timestamp createdTime;
    private Timestamp updatedTime;

    public Account() {}

    public Account(Account value) {
        this.id = value.id;
        this.userId = value.userId;
        this.emailAddress = value.emailAddress;
        this.hash = value.hash;
        this.createdTime = value.createdTime;
        this.updatedTime = value.updatedTime;
    }

    public Account(
        Integer   id,
        Integer   userId,
        String    emailAddress,
        String    hash,
        Timestamp createdTime,
        Timestamp updatedTime
    ) {
        this.id = id;
        this.userId = userId;
        this.emailAddress = emailAddress;
        this.hash = hash;
        this.createdTime = createdTime;
        this.updatedTime = updatedTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getEmailAddress() {
        return this.emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    public String getHash() {
        return this.hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    public Timestamp getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Timestamp createdTime) {
        this.createdTime = createdTime;
    }

    public Timestamp getUpdatedTime() {
        return this.updatedTime;
    }

    public void setUpdatedTime(Timestamp updatedTime) {
        this.updatedTime = updatedTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(emailAddress);
        sb.append(", ").append(hash);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(updatedTime);

        sb.append(")");
        return sb.toString();
    }
}
