/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryItem implements Serializable {

    private static final long serialVersionUID = -582117937;

    private Integer id;
    private String  name;
    private Integer categoryId;
    private String  extraInformation;
    private String  imageUrl;

    public CategoryItem() {}

    public CategoryItem(CategoryItem value) {
        this.id = value.id;
        this.name = value.name;
        this.categoryId = value.categoryId;
        this.extraInformation = value.extraInformation;
        this.imageUrl = value.imageUrl;
    }

    public CategoryItem(
        Integer id,
        String  name,
        Integer categoryId,
        String  extraInformation,
        String  imageUrl
    ) {
        this.id = id;
        this.name = name;
        this.categoryId = categoryId;
        this.extraInformation = extraInformation;
        this.imageUrl = imageUrl;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public String getExtraInformation() {
        return this.extraInformation;
    }

    public void setExtraInformation(String extraInformation) {
        this.extraInformation = extraInformation;
    }

    public String getImageUrl() {
        return this.imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CategoryItem (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(extraInformation);
        sb.append(", ").append(imageUrl);

        sb.append(")");
        return sb.toString();
    }
}
