/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoogleAccount implements Serializable {

    private static final long serialVersionUID = -1726629724;

    private Integer   id;
    private Integer   userId;
    private String    externalId;
    private Timestamp createdTime;
    private Timestamp updatedTime;

    public GoogleAccount() {}

    public GoogleAccount(GoogleAccount value) {
        this.id = value.id;
        this.userId = value.userId;
        this.externalId = value.externalId;
        this.createdTime = value.createdTime;
        this.updatedTime = value.updatedTime;
    }

    public GoogleAccount(
        Integer   id,
        Integer   userId,
        String    externalId,
        Timestamp createdTime,
        Timestamp updatedTime
    ) {
        this.id = id;
        this.userId = userId;
        this.externalId = externalId;
        this.createdTime = createdTime;
        this.updatedTime = updatedTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getExternalId() {
        return this.externalId;
    }

    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }

    public Timestamp getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Timestamp createdTime) {
        this.createdTime = createdTime;
    }

    public Timestamp getUpdatedTime() {
        return this.updatedTime;
    }

    public void setUpdatedTime(Timestamp updatedTime) {
        this.updatedTime = updatedTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GoogleAccount (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(externalId);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(updatedTime);

        sb.append(")");
        return sb.toString();
    }
}
