/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -2114802968;

    private Integer   id;
    private String    name;
    private String    profilePicture;
    private Timestamp createdTime;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.name = value.name;
        this.profilePicture = value.profilePicture;
        this.createdTime = value.createdTime;
    }

    public User(
        Integer   id,
        String    name,
        String    profilePicture,
        Timestamp createdTime
    ) {
        this.id = id;
        this.name = name;
        this.profilePicture = profilePicture;
        this.createdTime = createdTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getProfilePicture() {
        return this.profilePicture;
    }

    public void setProfilePicture(String profilePicture) {
        this.profilePicture = profilePicture;
    }

    public Timestamp getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Timestamp createdTime) {
        this.createdTime = createdTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(profilePicture);
        sb.append(", ").append(createdTime);

        sb.append(")");
        return sb.toString();
    }
}
