/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import se.olander.categories.jooq.DefaultCatalog;
import se.olander.categories.jooq.categories.tables.CategoryItems;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Categories extends SchemaImpl {

    private static final long serialVersionUID = -593662042;

    /**
     * The reference instance of <code>categories</code>
     */
    public static final Categories CATEGORIES = new Categories();

    /**
     * The table <code>categories.categories</code>.
     */
    public final se.olander.categories.jooq.categories.tables.Categories CATEGORIES_ = se.olander.categories.jooq.categories.tables.Categories.CATEGORIES_;

    /**
     * The table <code>categories.category_items</code>.
     */
    public final CategoryItems CATEGORY_ITEMS = se.olander.categories.jooq.categories.tables.CategoryItems.CATEGORY_ITEMS;

    /**
     * No further instances allowed
     */
    private Categories() {
        super("categories", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            se.olander.categories.jooq.categories.tables.Categories.CATEGORIES_,
            CategoryItems.CATEGORY_ITEMS);
    }
}
