/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import se.olander.categories.jooq.DefaultCatalog;
import se.olander.categories.jooq.categories.tables.Category;
import se.olander.categories.jooq.categories.tables.CategoryItem;
import se.olander.categories.jooq.categories.tables.Game;
import se.olander.categories.jooq.categories.tables.Guess;
import se.olander.categories.jooq.categories.tables.Participant;
import se.olander.categories.jooq.categories.tables.User;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Categories extends SchemaImpl {

    private static final long serialVersionUID = 224233026;

    /**
     * The reference instance of <code>categories</code>
     */
    public static final Categories CATEGORIES = new Categories();

    /**
     * The table <code>categories.category</code>.
     */
    public final Category CATEGORY = se.olander.categories.jooq.categories.tables.Category.CATEGORY;

    /**
     * The table <code>categories.category_item</code>.
     */
    public final CategoryItem CATEGORY_ITEM = se.olander.categories.jooq.categories.tables.CategoryItem.CATEGORY_ITEM;

    /**
     * The table <code>categories.game</code>.
     */
    public final Game GAME = se.olander.categories.jooq.categories.tables.Game.GAME;

    /**
     * The table <code>categories.guess</code>.
     */
    public final Guess GUESS = se.olander.categories.jooq.categories.tables.Guess.GUESS;

    /**
     * The table <code>categories.participant</code>.
     */
    public final Participant PARTICIPANT = se.olander.categories.jooq.categories.tables.Participant.PARTICIPANT;

    /**
     * The table <code>categories.user</code>.
     */
    public final User USER = se.olander.categories.jooq.categories.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Categories() {
        super("categories", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Category.CATEGORY,
            CategoryItem.CATEGORY_ITEM,
            Game.GAME,
            Guess.GUESS,
            Participant.PARTICIPANT,
            User.USER);
    }
}
