/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import se.olander.categories.jooq.categories.tables.Category;
import se.olander.categories.jooq.categories.tables.CategoryItem;
import se.olander.categories.jooq.categories.tables.Game;
import se.olander.categories.jooq.categories.tables.Participant;
import se.olander.categories.jooq.categories.tables.User;
import se.olander.categories.jooq.categories.tables.records.CategoryItemRecord;
import se.olander.categories.jooq.categories.tables.records.CategoryRecord;
import se.olander.categories.jooq.categories.tables.records.GameRecord;
import se.olander.categories.jooq.categories.tables.records.ParticipantRecord;
import se.olander.categories.jooq.categories.tables.records.UserRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>categories</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CategoryRecord, Integer> IDENTITY_CATEGORY = Identities0.IDENTITY_CATEGORY;
    public static final Identity<CategoryItemRecord, Integer> IDENTITY_CATEGORY_ITEM = Identities0.IDENTITY_CATEGORY_ITEM;
    public static final Identity<GameRecord, Integer> IDENTITY_GAME = Identities0.IDENTITY_GAME;
    public static final Identity<ParticipantRecord, Integer> IDENTITY_PARTICIPANT = Identities0.IDENTITY_PARTICIPANT;
    public static final Identity<UserRecord, Integer> IDENTITY_USER = Identities0.IDENTITY_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CategoryRecord> KEY_CATEGORY_PRIMARY = UniqueKeys0.KEY_CATEGORY_PRIMARY;
    public static final UniqueKey<CategoryItemRecord> KEY_CATEGORY_ITEM_PRIMARY = UniqueKeys0.KEY_CATEGORY_ITEM_PRIMARY;
    public static final UniqueKey<GameRecord> KEY_GAME_PRIMARY = UniqueKeys0.KEY_GAME_PRIMARY;
    public static final UniqueKey<ParticipantRecord> KEY_PARTICIPANT_PRIMARY = UniqueKeys0.KEY_PARTICIPANT_PRIMARY;
    public static final UniqueKey<ParticipantRecord> KEY_PARTICIPANT_UNIQ__USER_ID__GAME_ID = UniqueKeys0.KEY_PARTICIPANT_UNIQ__USER_ID__GAME_ID;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CategoryItemRecord, CategoryRecord> CATEGORY_ITEM_IBFK_1 = ForeignKeys0.CATEGORY_ITEM_IBFK_1;
    public static final ForeignKey<GameRecord, CategoryRecord> GAME_IBFK_1 = ForeignKeys0.GAME_IBFK_1;
    public static final ForeignKey<ParticipantRecord, UserRecord> PARTICIPANT_IBFK_1 = ForeignKeys0.PARTICIPANT_IBFK_1;
    public static final ForeignKey<ParticipantRecord, GameRecord> PARTICIPANT_IBFK_2 = ForeignKeys0.PARTICIPANT_IBFK_2;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<CategoryRecord, Integer> IDENTITY_CATEGORY = createIdentity(Category.CATEGORY, Category.CATEGORY.ID);
        public static Identity<CategoryItemRecord, Integer> IDENTITY_CATEGORY_ITEM = createIdentity(CategoryItem.CATEGORY_ITEM, CategoryItem.CATEGORY_ITEM.ID);
        public static Identity<GameRecord, Integer> IDENTITY_GAME = createIdentity(Game.GAME, Game.GAME.ID);
        public static Identity<ParticipantRecord, Integer> IDENTITY_PARTICIPANT = createIdentity(Participant.PARTICIPANT, Participant.PARTICIPANT.ID);
        public static Identity<UserRecord, Integer> IDENTITY_USER = createIdentity(User.USER, User.USER.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<CategoryRecord> KEY_CATEGORY_PRIMARY = createUniqueKey(Category.CATEGORY, "KEY_category_PRIMARY", Category.CATEGORY.ID);
        public static final UniqueKey<CategoryItemRecord> KEY_CATEGORY_ITEM_PRIMARY = createUniqueKey(CategoryItem.CATEGORY_ITEM, "KEY_category_item_PRIMARY", CategoryItem.CATEGORY_ITEM.ID);
        public static final UniqueKey<GameRecord> KEY_GAME_PRIMARY = createUniqueKey(Game.GAME, "KEY_game_PRIMARY", Game.GAME.ID);
        public static final UniqueKey<ParticipantRecord> KEY_PARTICIPANT_PRIMARY = createUniqueKey(Participant.PARTICIPANT, "KEY_participant_PRIMARY", Participant.PARTICIPANT.ID);
        public static final UniqueKey<ParticipantRecord> KEY_PARTICIPANT_UNIQ__USER_ID__GAME_ID = createUniqueKey(Participant.PARTICIPANT, "KEY_participant_uniq__user_id__game_id", Participant.PARTICIPANT.USER_ID, Participant.PARTICIPANT.GAME_ID);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<CategoryItemRecord, CategoryRecord> CATEGORY_ITEM_IBFK_1 = createForeignKey(se.olander.categories.jooq.categories.Keys.KEY_CATEGORY_PRIMARY, CategoryItem.CATEGORY_ITEM, "category_item_ibfk_1", CategoryItem.CATEGORY_ITEM.CATEGORY_ID);
        public static final ForeignKey<GameRecord, CategoryRecord> GAME_IBFK_1 = createForeignKey(se.olander.categories.jooq.categories.Keys.KEY_CATEGORY_PRIMARY, Game.GAME, "game_ibfk_1", Game.GAME.CATEGORY_ID);
        public static final ForeignKey<ParticipantRecord, UserRecord> PARTICIPANT_IBFK_1 = createForeignKey(se.olander.categories.jooq.categories.Keys.KEY_USER_PRIMARY, Participant.PARTICIPANT, "participant_ibfk_1", Participant.PARTICIPANT.USER_ID);
        public static final ForeignKey<ParticipantRecord, GameRecord> PARTICIPANT_IBFK_2 = createForeignKey(se.olander.categories.jooq.categories.Keys.KEY_GAME_PRIMARY, Participant.PARTICIPANT, "participant_ibfk_2", Participant.PARTICIPANT.GAME_ID);
    }
}
