/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import se.olander.categories.jooq.categories.tables.Categories;
import se.olander.categories.jooq.categories.tables.CategoryItems;
import se.olander.categories.jooq.categories.tables.records.CategoriesRecord;
import se.olander.categories.jooq.categories.tables.records.CategoryItemsRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>categories</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CategoriesRecord, Integer> IDENTITY_CATEGORIES_ = Identities0.IDENTITY_CATEGORIES_;
    public static final Identity<CategoryItemsRecord, Integer> IDENTITY_CATEGORY_ITEMS = Identities0.IDENTITY_CATEGORY_ITEMS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CategoriesRecord> KEY_CATEGORIES_PRIMARY = UniqueKeys0.KEY_CATEGORIES_PRIMARY;
    public static final UniqueKey<CategoryItemsRecord> KEY_CATEGORY_ITEMS_PRIMARY = UniqueKeys0.KEY_CATEGORY_ITEMS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CategoryItemsRecord, CategoriesRecord> CATEGORY_ITEMS_IBFK_1 = ForeignKeys0.CATEGORY_ITEMS_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<CategoriesRecord, Integer> IDENTITY_CATEGORIES_ = createIdentity(Categories.CATEGORIES_, Categories.CATEGORIES_.ID);
        public static Identity<CategoryItemsRecord, Integer> IDENTITY_CATEGORY_ITEMS = createIdentity(CategoryItems.CATEGORY_ITEMS, CategoryItems.CATEGORY_ITEMS.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<CategoriesRecord> KEY_CATEGORIES_PRIMARY = createUniqueKey(Categories.CATEGORIES_, "KEY_categories_PRIMARY", Categories.CATEGORIES_.ID);
        public static final UniqueKey<CategoryItemsRecord> KEY_CATEGORY_ITEMS_PRIMARY = createUniqueKey(CategoryItems.CATEGORY_ITEMS, "KEY_category_items_PRIMARY", CategoryItems.CATEGORY_ITEMS.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<CategoryItemsRecord, CategoriesRecord> CATEGORY_ITEMS_IBFK_1 = createForeignKey(se.olander.categories.jooq.categories.Keys.KEY_CATEGORIES_PRIMARY, CategoryItems.CATEGORY_ITEMS, "category_items_ibfk_1", CategoryItems.CATEGORY_ITEMS.CATEGORY_ID);
    }
}
