/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories;


import javax.annotation.Generated;

import se.olander.categories.jooq.categories.tables.Account;
import se.olander.categories.jooq.categories.tables.Category;
import se.olander.categories.jooq.categories.tables.CategoryItem;
import se.olander.categories.jooq.categories.tables.CategoryItemAlternativeSpelling;
import se.olander.categories.jooq.categories.tables.Game;
import se.olander.categories.jooq.categories.tables.GoogleAccount;
import se.olander.categories.jooq.categories.tables.Guess;
import se.olander.categories.jooq.categories.tables.Participant;
import se.olander.categories.jooq.categories.tables.User;


/**
 * Convenience access to all tables in categories
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>categories.account</code>.
     */
    public static final Account ACCOUNT = se.olander.categories.jooq.categories.tables.Account.ACCOUNT;

    /**
     * The table <code>categories.category</code>.
     */
    public static final Category CATEGORY = se.olander.categories.jooq.categories.tables.Category.CATEGORY;

    /**
     * The table <code>categories.category_item</code>.
     */
    public static final CategoryItem CATEGORY_ITEM = se.olander.categories.jooq.categories.tables.CategoryItem.CATEGORY_ITEM;

    /**
     * The table <code>categories.category_item_alternative_spelling</code>.
     */
    public static final CategoryItemAlternativeSpelling CATEGORY_ITEM_ALTERNATIVE_SPELLING = se.olander.categories.jooq.categories.tables.CategoryItemAlternativeSpelling.CATEGORY_ITEM_ALTERNATIVE_SPELLING;

    /**
     * The table <code>categories.game</code>.
     */
    public static final Game GAME = se.olander.categories.jooq.categories.tables.Game.GAME;

    /**
     * The table <code>categories.google_account</code>.
     */
    public static final GoogleAccount GOOGLE_ACCOUNT = se.olander.categories.jooq.categories.tables.GoogleAccount.GOOGLE_ACCOUNT;

    /**
     * The table <code>categories.guess</code>.
     */
    public static final Guess GUESS = se.olander.categories.jooq.categories.tables.Guess.GUESS;

    /**
     * The table <code>categories.participant</code>.
     */
    public static final Participant PARTICIPANT = se.olander.categories.jooq.categories.tables.Participant.PARTICIPANT;

    /**
     * The table <code>categories.user</code>.
     */
    public static final User USER = se.olander.categories.jooq.categories.tables.User.USER;
}
