/*
 * This file is generated by jOOQ.
*/
package se.olander.categories.jooq.categories;


import javax.annotation.Generated;

import se.olander.categories.jooq.categories.tables.Categories;
import se.olander.categories.jooq.categories.tables.CategoryItems;


/**
 * Convenience access to all tables in categories
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>categories.categories</code>.
     */
    public static final Categories CATEGORIES_ = se.olander.categories.jooq.categories.tables.Categories.CATEGORIES_;

    /**
     * The table <code>categories.category_items</code>.
     */
    public static final CategoryItems CATEGORY_ITEMS = se.olander.categories.jooq.categories.tables.CategoryItems.CATEGORY_ITEMS;
}
